In [1]:
import numpy as np
import sys

In [17]:
# 51.如何为numpy中的数组生成独热编码（one-hot encodings）？
# 难度：4
# 问题：计算独热编码。
# 输入：

np.random.seed(101)
arr = np.random.randint(1,4,size=6)


# Solution:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

one_hot_encodings(arr)


array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [16]:
print (arr)
for i, v in enumerate(arr):
    print(i,v)

[2 3 2 2 2 1]
0 2
1 3
2 2
3 2
4 2
5 1


In [18]:
# 52.如何创建按分类变量分组的行号？
# 难度：3
# 问题：创建由分类变量分组的行号。使用iris的species中的样品作为输入。
# 输入：

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
#species_small

print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small == val])])


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'],
      dtype='<U15')

In [23]:
# 53.如何根据给定的分类变量创建分组ID？
# 难度：4
# 问题：根据给定的分类变量创建组ID。使用以下iris的species中样品作为输入。
# 输入：
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))

np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))

# Solution:
output = [np.argwhere(np.unique(species_small_ == s).tolist()[0][0] 
                      for val in np.unique(species_small) 
                      for s in species_small[species_small])]

# Solution: For Loop version
output = []
uniqs = np.unique(species_small)

for val in uniqs: # uniq values in group
    for s in species_small[species_small==val]: # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0] # groupid
        output.append(groupid)
        
print(output)


[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [26]:
# 54.如何使用numpy排列数组中的元素？
# 难度：2
# 问题：为给定的数字数组a排序。
# 输入：
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

# Solution
print(a.argsort().argsort())
print('Array: ', a)


Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [27]:
# 55.如何使用numpy对多维数组中的元素进行排序？
# 难度：3
# 问题：创建一个与给定数字数组a相同形式的排列数组。
# 输入：

# Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

# Solution
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]
