In [1]:
import numpy as np

In [2]:
# level 2
# find the common elements between list a and b 

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [3]:
# 12
# a - b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [4]:
# 13
# level 2
# find the indexing number of list a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [5]:
# 14
# level 2
# extract all the elements between 5 and 10 from list a

a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]




array([ 5,  6,  7,  8,  9, 10])

In [6]:
# 15
# level 2
# deal with two-scaler-function maxx running on two arraies

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


pair_max = np.vectorize(maxx, otypes = [float])
    
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a,b)



array([6., 7., 9., 8., 9., 7., 5.])

In [7]:
# 16 
# level 2
# swap the 1st and 2nd column of an array

arr = np.arange(9).reshape(3,3)
arr 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [9]:
# 17
# level 2
# swap the first and second row of an array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr = np.arange(9).reshape(3,3)

# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [11]:
# 18
# level 2
# reverse rows of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [13]:
# 19 
# level 2
# reverse columns of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [15]:
# 20
# level 2
# Create a 5*3 matrix which contains float numbers from 5 to 10

arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint( low = 5, high=10, size=(5,3) ) + np.random.random((5,3))

print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3))
print(rand_arr)
                             
                             

[[5.89456761 8.12432103 5.27562216]
 [8.45407991 7.39129069 8.51814172]
 [5.55257337 5.22958125 5.90701279]
 [5.00448652 6.98736688 9.72699588]
 [6.62306694 8.91956294 9.00786865]]
[[6.80664744 8.73101955 6.33163824]
 [5.56097201 8.14225306 7.83649712]
 [8.44277506 7.79739542 5.03355201]
 [6.36033472 9.73631877 7.44168657]
 [8.78579518 7.88526791 7.96577457]]


In [16]:
# 21
# level 1
# print python numpy array and reserve the first 3 digits
rand_arr = np.random.random((5,3))
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision = 3)
rand_arr[:4]


array([[0.341, 0.361, 0.527],
       [0.781, 0.613, 0.394],
       [0.122, 0.772, 0.192],
       [0.073, 0.081, 0.285]])

In [19]:
# 22
# level 1
# use secitific style e.g. 1e10 to print a numpy array

# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [20]:
# 23-
# level 1
# limit the number of elements in python numpy array a to 6

np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [24]:
# 24
# level 1
# print the complete numpy array a without interrupt

# Input
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

# Solution
np.set_printoptions(threshold=np.nan)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
# 25
# level 2
# how to import number and text data set with the technique from python numpy without lossing completment

# import iris dataset without the change of text
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# print the first 3 rows
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [33]:
# 26
# level 3
# how to extract a column from a 1-D meta data

# Input
import sys
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution
species = np.array([row[4] for row in iris_1d])
species[:5]



(150,)


C:\Users\bejin\Anaconda3\envs\mlbook\lib\site-packages\ipykernel_launcher.py:8: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [35]:
# 27
# level 2
# convert 1d data into 2d data 
# convert 1d iris array into 2d data iris_2d by omiting species text data

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Solution:
# Method 1: Covert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 oclumns form source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

C:\Users\bejin\Anaconda3\envs\mlbook\lib\site-packages\ipykernel_launcher.py:8: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  
C:\Users\bejin\Anaconda3\envs\mlbook\lib\site-packages\ipykernel_launcher.py:10: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  # Remove the CWD from sys.path while we load stuff.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [37]:
# 28
# level 1
# find the mean, median, and standard diviation

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)


5.843333333333334 5.8 0.8253012917851409


In [38]:
# 29
# level e
# normalize an array to the values between 0~1

# create a normalized iris from sepallength, the values are between 0~1, the minimum is 0, and the maximum is 1
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)



[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


In [41]:
# 30
# level 3
# how to calculate softmax value

# calculate sepallength softmax value
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


In [42]:
# 31 
# level 1
# how to find a numpy array percent digit value

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
np.percentile(sepallength, q=[5, 95])


array([4.6  , 7.255])

In [99]:
# 32
# level 2
# insert np.nan in 20 random positons in a 2-D data set iris_2d

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)


# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(int(time.clock() * 1e3 ))
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan


# Method 2
np.random.seed(int(time.clock() * 1e3 ))
iris_2d[np.random.randint(150, size=20), np.random.randint(5, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' nan b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [103]:
# 33
# level 2
# Find the missing spot of an array

# find the number of missing values and their positions from iris_2d in sepallength
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4,size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:,0])))


Number of missing values: 
 5
Position of missing values: 
 (array([ 38,  47,  59, 126, 138], dtype=int64),)


In [ ]:
import time

tick = int(time.clock() * 1e3 )
#print ("tick%d", tick)
np.random.seed(tick)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))