In [1]:
import numpy as np
import sys

In [2]:
# 51.如何为numpy中的数组生成独热编码（one-hot encodings）？
# 难度：4
# 问题：计算独热编码。
# 输入：

np.random.seed(101)
arr = np.random.randint(1,4,size=6)


# Solution:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

one_hot_encodings(arr)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [3]:
print (arr)
for i, v in enumerate(arr):
    print(i,v)

[2 3 2 2 2 1]
0 2
1 3
2 2
3 2
4 2
5 1


In [4]:
# 52.如何创建按分类变量分组的行号？
# 难度：3
# 问题：创建由分类变量分组的行号。使用iris的species中的样品作为输入。
# 输入：

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
#species_small

print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small == val])])


[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
# 53.如何根据给定的分类变量创建分组ID？
# 难度：4
# 问题：根据给定的分类变量创建组ID。使用以下iris的species中样品作为输入。
# 输入：
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))

np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))

# Solution:
output = [np.argwhere(np.unique(species_small_ == s).tolist()[0][0] 
                      for val in np.unique(species_small) 
                      for s in species_small[species_small])]

# Solution: For Loop version
output = []
uniqs = np.unique(species_small)

for val in uniqs: # uniq values in group
    for s in species_small[species_small==val]: # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0] # groupid
        output.append(groupid)
        
print(output)


[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [6]:
# 54.如何使用numpy排列数组中的元素？
# 难度：2
# 问题：为给定的数字数组a排序。
# 输入：
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

# Solution
print(a.argsort().argsort())
print('Array: ', a)


Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [7]:
# 55.如何使用numpy对多维数组中的元素进行排序？
# 难度：3
# 问题：创建一个与给定数字数组a相同形式的排列数组。
# 输入：

# Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

# Solution
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [9]:
# 56.如何找到numpy二维数组每一行中的最大值？
# 难度：2
# 问题：计算给定数组中每一行的最大值。

# Input
np.random.seed(100)
a = np.random.randint(1, 10, [5,3])

# Solution 1
np.amax(a, axis = 1)

# Solution 2
np.apply_along_axis(np.max, arr=a, axis=1)


array([9, 8, 6, 3, 9])

In [12]:
# 57.如何计算numpy二维数组每行中的最小值？
# 难度：3
# 问题：针对给定的二维numpy数组计算每行的min-max。

# Input
np.random.seed(100)
a = np.random.randint(1, 10, [5, 3])

# Solution
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [15]:
# 58.如何在numpy数组中找到重复的记录？
# 难度：3
# 问题：在给定的numpy数组中找到重复的条目（从第2个起），并将它们标记为True。第一次出现应该是False。

# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

print('Array', a)

# Solution
# There is no direct function to do this as of 1.13.3
# Create an all True array

out = np.full(a.shape[0], True)

# Find the index positions of unque elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)

Array [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [14]:
np.unique(a, return_index=True)

(array([0, 2, 3, 4]), array([0, 4, 2, 5], dtype=int64))

In [16]:
# 59.如何找到numpy中的分组平均值？
# 难度：3
# 问题：查找由二维numpy数组中的分类列分组的数值列的平均值

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float') # sepalwidth
grouping_column = iris[:, 4] # species

# List comprehension version
[[group_val, numeric_column[grouping_column == group_val].mean()] for group_val in np.unique(grouping_column)]

# For Loop version
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column == group_val].mean()])
    
output


[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [21]:
# 60.如何将PIL图像转换为numpy数组？
# 难度：3
# 问题：从以下URL中导入图像并将其转换为numpy数组。
# URL='https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

from io import BytesIO
from PIL import Image
import PIL, requests

# Import image form URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150, 150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)