In [4]:
import numpy as np

In [5]:
# level 2
# find the common elements between list a and b 

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [6]:
# 12
# a - b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [7]:
# 13
# level 2
# find the indexing number of list a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [9]:
# 14
# level 2
# extract all the elements between 5 and 10 from list a

a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]




array([ 5,  6,  7,  8,  9, 10])

In [11]:
# 15
# level 2
# deal with two-scaler-function maxx running on two arraies

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


pair_max = np.vectorize(maxx, otypes = [float])
    
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a,b)



array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [14]:
# 16 
# level 2
# swap the 1st and 2nd column of an array

arr = np.arange(9).reshape(3,3)
arr 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [18]:
# 17
# level 2
# swap the first and second row of an array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr = np.arange(9).reshape(3,3)

# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [20]:
# 18
# level 2
# reverse rows of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [22]:
# 19 
# level 2
# reverse columns of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [27]:
# 20
# level 2
# Create a 5*3 matrix which contains float numbers from 5 to 10

arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint( low = 5, high=10, size=(5,3) ) + np.random.random((5,3))

print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3))
print(rand_arr)
                             
                             

[[ 7.346097    9.48798167  9.62665018]
 [ 8.44105375  9.88931419  9.6282867 ]
 [ 7.88296512  7.68639299  6.92986366]
 [ 6.48580573  8.00215893  8.90760369]
 [ 5.86048112  5.44532715  8.92847513]]
[[ 6.36689346  7.68744528  7.77462331]
 [ 9.51340416  7.39273163  5.13778957]
 [ 6.94167424  7.39662875  6.51885992]
 [ 9.10792562  6.86548806  9.70379875]
 [ 5.83856311  9.42706942  9.0093593 ]]


In [11]:
# 21
# level 1
# print python numpy array and reserve the first 3 digits
rand_arr = np.random.random((5,3))
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision = 3)
rand_arr[:4]


array([[ 0.088,  0.85 ,  0.73 ],
       [ 0.439,  0.098,  0.51 ],
       [ 0.782,  0.155,  0.008],
       [ 0.182,  0.953,  0.391]])

In [13]:
# 22
# level 1
# use secitific style e.g. 1e10 to print a numpy array

# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3
ran_arr

array([[  5.434e-04,   2.784e-04,   4.245e-04],
       [  8.448e-04,   4.719e-06,   1.216e-04],
       [  6.707e-04,   8.259e-04,   1.367e-04]])

In [15]:
# 23-
# level 1
# limit the number of elements in python numpy array a to 6

np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])