In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.13.3


In [6]:
# level 1
# create an array : [0-9]
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.full((3,3), True, dtype=bool)
# alternate method
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [11]:
# Input
arr = np.array([0,1,2,3,4,5,6,7,8,9])

#Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [13]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
# level 2
# replace without aggecting the original data
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1 , arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
# reconstruct array
arr = np.arange(10)
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
# level 2
# how to merge two arraies a and b
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# method 1
np.concatenate([a,b], axis=0)

# method 2
np.vstack([a, b])

# method 3
np.r_[a, b]



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# level 2
# merge two arraies harizentaly
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# method 1
np.concatenate([a, b], axis = 1)

# method 2 
np.hstack([a, b])

# method 3
np.c_[a, b]



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [31]:
# level 2
# create the following mode without hard coding. Use numpy functions and input of list a only.

a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])