In [2]:
import numpy as np

In [3]:
# level 2
# find the common elements between list a and b 

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [4]:
# 12
# a - b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [5]:
# 13
# level 2
# find the indexing number of list a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [6]:
# 14
# level 2
# extract all the elements between 5 and 10 from list a

a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]




array([ 5,  6,  7,  8,  9, 10])

In [7]:
# 15
# level 2
# deal with two-scaler-function maxx running on two arraies

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


pair_max = np.vectorize(maxx, otypes = [float])
    
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a,b)



array([6., 7., 9., 8., 9., 7., 5.])

In [8]:
# 16 
# level 2
# swap the 1st and 2nd column of an array

arr = np.arange(9).reshape(3,3)
arr 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [10]:
# 17
# level 2
# swap the first and second row of an array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr = np.arange(9).reshape(3,3)

# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [12]:
# 18
# level 2
# reverse rows of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [14]:
# 19 
# level 2
# reverse columns of 2D array

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [16]:
# 20
# level 2
# Create a 5*3 matrix which contains float numbers from 5 to 10

arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint( low = 5, high=10, size=(5,3) ) + np.random.random((5,3))

print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3))
print(rand_arr)
                             
                             

[[7.13690451 6.85587103 6.43017917]
 [7.95801108 6.59856246 8.58265032]
 [9.14697687 5.32950455 6.60901272]
 [8.2668444  5.5384325  7.26515912]
 [7.25226355 9.01014471 7.97020438]]
[[6.88592775 7.84630657 7.14483128]
 [8.06299241 5.37973506 8.73395682]
 [9.25195664 8.26592716 6.37690244]
 [6.30742452 9.25950277 8.41245538]
 [6.33842485 5.15547409 9.43507305]]


In [17]:
# 21
# level 1
# print python numpy array and reserve the first 3 digits
rand_arr = np.random.random((5,3))
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision = 3)
rand_arr[:4]


array([[0.009, 0.609, 0.588],
       [0.182, 0.173, 0.169],
       [0.013, 0.078, 0.177],
       [0.723, 0.927, 0.322]])

In [18]:
# 22
# level 1
# use secitific style e.g. 1e10 to print a numpy array

# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [19]:
# 23-
# level 1
# limit the number of elements in python numpy array a to 6

np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [20]:
# 24
# level 1
# print the complete numpy array a without interrupt

# Input
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

# Solution
np.set_printoptions(threshold=np.nan)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
# 25
# level 2
# how to import number and text data set with the technique from python numpy without lossing completment

# import iris dataset without the change of text
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# print the first 3 rows
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [22]:
# 26
# level 3
# how to extract a column from a 1-D meta data

# Input
import sys
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution
species = np.array([row[4] for row in iris_1d])
species[:5]



(150,)


C:\Users\bejin\Anaconda3\envs\mlbook\lib\site-packages\ipykernel_launcher.py:8: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [23]:
# 27
# level 2
# convert 1d data into 2d data 
# convert 1d iris array into 2d data iris_2d by omiting species text data

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Solution:
# Method 1: Covert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 oclumns form source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

C:\Users\bejin\Anaconda3\envs\mlbook\lib\site-packages\ipykernel_launcher.py:8: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [24]:
# 28
# level 1
# find the mean, median, and standard diviation

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)


5.843333333333334 5.8 0.8253012917851409


In [25]:
# 29
# level e
# normalize an array to the values between 0~1

# create a normalized iris from sepallength, the values are between 0~1, the minimum is 0, and the maximum is 1
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)



[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


In [26]:
# 30
# level 3
# how to calculate softmax value

# calculate sepallength softmax value
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


In [27]:
# 31 
# level 1
# how to find a numpy array percent digit value

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
np.percentile(sepallength, q=[5, 95])


array([4.6  , 7.255])

In [28]:
# 32
# level 2
# insert np.nan in 20 random positons in a 2-D data set iris_2d

import time

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)


# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(int(time.clock() * 1e3 ))
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan


# Method 2
np.random.seed(int(time.clock() * 1e3 ))
iris_2d[np.random.randint(150, size=20), np.random.randint(5, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [nan b'3.1' b'1.5' nan b'Iris-setosa']]


In [29]:
# 33
# level 2
# Find the missing spot of an array

# find the number of missing values and their positions from iris_2d in sepallength
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4,size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:,0]))) # np.where only returns the index


Number of missing values: 
 6
Position of missing values: 
 (array([ 42,  53,  65,  79, 102, 120], dtype=int64),)


In [30]:
# 34
# level 3
# 问题：过滤具有petallength（第3列）> 1.5和sepallength（第1列）<5.0的iris_2d的行。

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:,2] < 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]
#iris_2d [np.where(iris_2d[:, 2] < 1.5)]




array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2]])

In [31]:
# 35
# Level 3
# 问题：选择没有nan值的iris_2d数组的行

#Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#Solution
import time
tick = int(time.clock()*1e3)
np.random.seed(tick)
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan

# No direct numpy funciton for this
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
# any_nan_in_row
iris_2d[any_nan_in_row][:5]



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [32]:
# 36
# level 2
# 问题：在iris_2d数组中查找SepalLength（第1列）和PetalLength（第3列）之间的关系。

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

# Solution 2
from scipy.stats.stats import pearsonr
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)

# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1

# The p-value roughly indicated the probability of an uncorrelated system producing
# datesets that have a correlation at least as extreme as the one computed. 
# The lower the p-value (< 0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.




0.8717541573048712


In [33]:
# 37.如何查找给定数组是否有空值？ 
# level 2
# 问题：找出数组iris_2d是否有缺失的值。

#Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()


False

In [34]:
# 38.如何在numpy数组中使用0替换所有缺失值？
# level 2
# 问题：在numpy数组中用0替换nan。

#Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan

# Solution
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [35]:
# 39.如何查找numpy数组中的唯一值的数量？
# 难度：2
# 问题：找出iris的species中的唯一值及其数量。

# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
uniArr = np.unique(species, return_counts = True)


In [36]:
# 40.如何将数值转换为分类（文本）数组？
# 难度：2
# 问题：将iris_2d的花瓣长度（第3列）组成一个文本数组，如果花瓣长度为：
#    <3则为'小'
#    3-5则为'中'
#    '> = 5则为'大'

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View 
petal_length_cat[:4]



['small', 'small', 'small', 'small']

In [37]:
# 41.如何利用numpy数组现有列创建一个新的列？
# 难度：2
# 问题：在iris_2d中为volume创建一个新列，其中volume是（pi x petallength x sepal_length ^ 2）/ 3。

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength ** 2))/3
#print(volume)
v1 = volume
# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis] # np.newaxis = None
#print(volume)
# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:4]


array([[ 5.1  ,  3.5  ,  1.4  ,  0.2  , 38.133],
       [ 4.9  ,  3.   ,  1.4  ,  0.2  , 35.2  ],
       [ 4.7  ,  3.2  ,  1.3  ,  0.2  , 30.072],
       [ 4.6  ,  3.1  ,  1.5  ,  0.2  , 33.238]])

In [38]:
# 42.如何在numpy中进行概率抽样？
# 难度：3
# 问题：随机抽样iris的species，使setose是versicolor和virginica的数量的两倍。

# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

# Approach 2: Probablistic Sampling (prefered)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

# 方法2是首选，因为它创建了一个可用于采样二维表格数据的索引变量。

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36], dtype=int64))


In [39]:
# 43.用另一个数组分组时，如何获得数组中第二大的元素值？
# 难度：2
# 问题：第二长的物种的最大价值是什么？

# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

# Get the second last vale
np.unique(np.sort(petal_len_setosa))[-2]


1.7

In [40]:
# 44.如何按列排序二维数组？
# 难度：2
# 问题：根据sepallength列对iris数据集进行排序。


# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Sort by column position 0: SepalLength
print(iris[iris[:, 0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [41]:
iris[:, 0].argsort()

array([ 13,  42,  38,   8,  41,  22,   3,   6,  47,   2,  29,  12,  45,
        24,  11,  30,  57, 106,  34,   9,  37,   1,  40,  26,  49,  35,
        43,  60,   7,  93,   4,  25,  44,  46,  98,   0,  39,  17,  23,
        21,  19,  32,  28,  27,  59,  48,  84,   5,  20,  31,  10,  16,
        36,  90,  33,  53,  81,  80,  89,  88, 121,  66,  69,  94,  64,
        79,  96,  99,  15,  55, 113,  18,  95,  67,  14,  92, 114, 142,
        82, 101, 149,  61,  70,  78,  83, 138,  85,  62, 119, 127, 134,
        71,  63,  73,  91,  68,  97, 148, 126,  72, 123, 146,  56, 133,
       100,  87, 136, 103, 132, 128, 137,  51, 115,  74, 111, 104, 116,
       147,  54, 110,  58,  75,  86, 140, 108,  77,  65, 144, 145, 124,
       143,  76, 112, 139, 141,  52, 120,  50, 102, 129, 125, 109, 107,
       130, 105, 122, 118, 117, 135, 131], dtype=int64)

In [42]:
# 45.如何在numpy数组中找到最频繁出现的值？
# 难度：1
# 问题：找到iris数据集中最常见的花瓣长度值（第3列）。


# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution:
vals, counts = np.unique(iris[:, 3], return_counts=True)
print(vals[np.argmax(counts)])


b'0.2'


In [43]:
counts, np.argmax(counts)

(array([ 6, 28,  7,  7,  1,  1,  7,  3,  5, 13,  8, 12,  4,  2, 12,  5,  6,
         6,  3,  8,  3,  3], dtype=int64), 1)

In [44]:
# 46.如何找到首次出现的值大于给定值的位置？
# 难度：2
# 问题：查找在iris数据集的第4列花瓣宽度中第一次出现值大于1.0的位置。

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution:
print(np.argmax(iris[:, 3].astype('float') > 1.0))



50


In [45]:
# 47.如何将所有大于给定值的值替换为给定的cutoff值？
# 难度：2
# 问题：从数组a中，替换大于30包括30且小于10到10的所有值。

# Input
np.set_printoptions(precision = 2)
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

# Solution 1: Using np.clip
np.clip(a, a_min=10, a_max=30)

# Solution 2: Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))



[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [50]:
np.where([[True, False], [True, True]], 
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

In [53]:
x = 2
y = 3
np.where( x > y, x, y)

array(3)

In [54]:
# 48.如何从numpy数组中获取n个值的位置？
# 难度：2
# 问题：获取给定数组a中前5个最大值的位置。

# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

# Solution:
print(a[a.argsort()][-5:])


[41.   41.47 42.39 44.67 48.95]


In [117]:
# 49.如何计算数组中所有可能值的行数？
# 难度：4
# 问题：计算有唯一值的行数。


# 输入：
import time
tick = int(time.clock()*1e3)
np.random.seed(tick)
arr = np.random.randint(1, 11, size=(6,10))
# 输出包含10列，表示1到10之间的数字。这些值是相应行中数字数量。
# 例如，单元（0,2）的值为2，这意味着数字3在第一行中恰好出现2次。

# Solution
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    
    # Counts of all values row wise
    return ([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
# print(np.arange(1, 11))
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


[[3, 1, 1, 0, 1, 0, 1, 2, 0, 1],
 [1, 0, 1, 0, 0, 0, 3, 1, 2, 2],
 [1, 0, 0, 0, 0, 1, 0, 3, 4, 1],
 [4, 1, 0, 1, 1, 0, 1, 0, 2, 0],
 [1, 2, 0, 1, 1, 1, 2, 0, 2, 0],
 [2, 0, 1, 1, 1, 0, 0, 2, 2, 1]]

In [118]:
arr2 = np.random.randint(1, 11, size=(2,10))

# num_counts_array
num_counts_array = [np.unique(row, return_counts=True) for row in arr2]
print("num_counts_array:\n", num_counts_array)

# A
[print("a,b: \n", a, b) for a, b in num_counts_array]
# print("A:\n", A)



num_counts_array:
 [(array([ 1,  2,  4,  6,  9, 10]), array([1, 1, 3, 1, 3, 1], dtype=int64)), (array([1, 2, 4, 5, 7, 8, 9]), array([1, 2, 1, 3, 1, 1, 1], dtype=int64))]
a,b: 
 [ 1  2  4  6  9 10] [1 1 3 1 3 1]
a,b: 
 [1 2 4 5 7 8 9] [1 2 1 3 1 1 1]


[None, None]

In [59]:
# 50.如何将多维数组转换为一维数组？
# 难度：2
# 问题：将array_of_arrays转换为平坦的线性一维数组。

# Input
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
print(arr_2d)


array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


In [46]:
import time

tick = int(time.clock() * 1e3 )
#print ("tick%d", tick)
np.random.seed(tick)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))
np.random.seed(100)
print(np.random.randint(10))

3
8
8
8
